server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
    username: ran
    password: 9151
  thymeleaf:
    enabled: true
    cache: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
          dialect: org.hibernate.dialect.MariaDBDialect

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

upload:
  dir: /Users/hyeranpakr/Desktop/happy/9.14/shop/src/main/resources/static/upload

itemImgLocation: /Users/hyeranpakr/Desktop/happy/9.14/shop/src/main/resources/static/images
uploadPath: /Users/hyeranpakr/Desktop/happy/9.14/shop/src/main/resources/static/uploadPath
